# File: .github/workflows/workflow.yml

on: [workflow_dispatch]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
# name: Azure Login Test
# on: 
#   workflow_dispatch:
#   # call the workflow

# permissions:
#   id-token: write
#   contents: read
      
# jobs: 
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Prase AZURE_MSI secret
#       id: msiPrincipal
#       env:
#         SECRET: ${{ secrets.AZURE_MSI }}
#       run: |
#         clientId=$(echo $SECRET | jq -r '.["clientId"]')
#         tenantId=$(echo $SECRET | jq -r '.["tenantId"]')
#         subscriptionId=$(echo $SECRET | jq -r '.["id"] | split("/")[2]')
#         echo "::add-mask::$clientId"
#         echo "::add-mask::$tenantId"
#         echo "::add-mask::$subscriptionId"
#         echo clientId=$clientId >> $GITHUB_OUTPUT
#         echo tenantId=$tenantId >> $GITHUB_OUTPUT
#         echo subscriptionId=$subscriptionId >> $GITHUB_OUTPUT

#     # Login
#     - name: 'Azure login'
#       uses: azure/login@v1
#       with:
#         client-id: ${{ steps.msiPrincipal.outputs.clientId }}
#         tenant-id: ${{ steps.msiPrincipal.outputs.tenantId }}
#         subscription-id: ${{ steps.msiPrincipal.outputs.subscriptionId }}
#     # Logout
#     - name: 'Azure logout'
#       run: |
#         az logout
#       if: always()