name: Build and publish
on:
   
  workflow_dispatch:
    inputs:
      AZ_ACR_NAME: 
        type: string
        description: 'Azure Function App name'
        required: true

permissions:
  id-token: write
  contents: read
      
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      id: msiPrincipal
      env:
        SECRET: ${{ secrets.AZURE_MSI }}
    steps:
    # Login
    - name: 'Azure login'
      uses: azure/login@v1
      with:
        client-id: ${{ steps.msiPrincipal.outputs.clientId }}
        tenant-id: ${{ steps.msiPrincipal.outputs.tenantId }}
        subscription-id: ${{ steps.msiPrincipal.outputs.subscriptionId }}

    - name: Build and deploy Container App
      uses: azure/container-apps-deploy-action@v1
      with:
        appSourcePath: ${{ github.workspace }}
        acrName: AZ_ACR_NAME
    # Logout
    - name: 'Azure logout'
      run: |    
        az logout
      if: always()